#!/usr/bin/ruby

require 'yaml'
require 'etcd'

class EtcdImport

  def initialize
    (@yaml_filename, @tree_root) = ARGV
    @tree_root ||= ""
    @etcd = etcd_connect
    @hash = read_config
    import_structure @hash, @tree_root
  end

  def import_structure (hash, path="")
    begin
      hash.each do |k, v|
        etcd_key = path + "/" + k.to_s
        case v
        when Hash
          import_structure(v, etcd_key)
        else
          @etcd.set(etcd_key, value: v)
          puts "SET: " + etcd_key + ": " + v.to_json
        end
      end
    rescue Exception => e
      $stderr.puts "Configuration import failed"
      $stderr.puts e.message
      exit! 1
    end
  end

  def read_config
    begin
      return YAML.load_file(@yaml_filename)
    rescue
      $stderr.puts "Couldn't parse YAML file definitions"
      exit! 1
    end
  end

  def etcd_connect
    ENV['ETCD_HOST'] ||= "127.0.0.1"
    host = ENV['ETCD_HOST'] || "127.0.0.1"
    @etcd = Etcd.client(host: ENV['ETCD_HOST'], port: 4001)
    @etcd.leader
    begin
      @etcd.leader
      return @etcd
    rescue
      $stderr.puts "Couldn't connect to etcd at #{ENV['ETCD_URL']}"
      exit! 1
    end
  end

end

EtcdImport.new
