#!/usr/bin/ruby

require 'yaml'
require 'etcd'

class EtcdImport

  def initialize
    (@yaml_filename, @tree_root) = ARGV
    @tree_root ||= ""

    # check if we know ETCD_URL otherwise use a sane default
    ENV['ETCD_URL'] ||= "etcd://127.0.0.1:4001/"

    # initialize ETCD client
    (etcd_host, etcd_port) = ENV['ETCD_URL'].sub(/^etcd:\/\//, '').sub(/\/$/, '').split(':')
    @etcd = Etcd.client(host: etcd_host, port: etcd_port)

    # read YAML file
    begin
      @hash = YAML.load_file(@yaml_filename)
    rescue
      $stderr.puts "Couldn't parse YAML file definitions"
      exit 1
    end

    # ETCD connection check
    begin
      @etcd.leader
    rescue
      $stderr.puts "Couldn't connect to etcd at #{ENV['ETCD_URL']}"
      # exit 1
    end

    begin
      import_structure @hash, @tree_root
    rescue
      $stderr.puts "Configuration import failed"
      exit 1
    end
  end

  def import_structure (hash, path="")
    hash.each do |k, v|
      etcd_key = path + "/" + k.to_s
      case v
      when Hash
        import_structure(v, etcd_key)
      else
        # @etcd.set(etcd_key, value: v.to_json)
        puts etcd_key + ": " + v.to_json
      end
    end
  end

end

EtcdImport.new
