#!/usr/bin/ruby

require 'yaml'
require 'erb'
require 'etcd'
require 'optparse'

class EtcdERB < ERB

  attr_reader :etcd

  def initialize
    self.optparse
    @etcd = self.class.connect(@options[:host], @options[:port])
    super self.class.template
    puts self.result
  end

  def optparse
    @options = Hash.new

    @options[:host] = ENV['ETCD_HOST']
    @options[:port] = ENV['ETCD_PORT']

    @options[:host] ||= "127.0.0.1"
    @options[:port] ||= 4001

    OptionParser.new do |opts|
      opts.banner = "Applies variables from ETCD onto ERB template\n\nUsage: #{$0} [OPTIONS] < template.erb > outfile"
      opts.separator ""
      opts.separator "Connection options:"
      opts.on("-s", "--host HOST", "hostname/IP of the ETCD service (ETCD_HOST envvar also applies) [DEFAULT: 127.0.0.1]") do |param|
        @options[:host] = param
      end
      opts.on("-p", "--port PORT", "port of the ETCD service (ETCD_PORT envvar also applies) [DEFAULT: 4001]") do |param|
        @options[:port] = param
      end
      opts.separator ""
      opts.separator "Common options:"
      opts.on_tail("-h", "--help", "show usage") do |param|
        puts opts;
        exit! 0
      end
    end.parse!
  end

  def result
    super binding
  end

  def value path
    return @etcd.get('/' + path.sub(/^\//, '')).value
  end

  def keys path
    path.sub!(/^\//, '')
    if @etcd.get('/' + path).directory?
      return @etcd.get('/' + path).children.map { |key| key.key }
    else
      return []
    end
  end

  class << self

    def connect (host, port)
      etcd = Etcd.client(host: host, port: port)
      begin
        etcd.version
        return etcd
      rescue Exception => e
        $stderr.puts "Couldn't connect to etcd at #{host}:#{port}"
        $stderr.puts e.message
        exit! 1
      end
    end

    def template
      ARGF.read
    end

  end


end

EtcdERB.new
